# frozen_string_literal: true

source 'https://rubygems.org'

# Test Kitchen with proxy driver
gem 'test-kitchen', '~> 3.6'
gem 'kitchen-inspec', '~> 2.6'

# Berkshelf for cookbook dependency management
gem 'berkshelf', '~> 8.0'

# InSpec for verification
gem 'inspec', '~> 6.8'
