# frozen_string_literal: true

source 'https://rubygems.org'

# Cookstyle for Chef cookbook linting (replaces Foodcritic)
# Cookstyle bundles its own RuboCop version
gem 'cookstyle', '~> 7.32'

# Development dependencies
group :development do
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.12'
end
