# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'cookstyle', '~> 7.0'
gem 'rubocop', '>= 1.25.0'

group :development do
  gem 'bundler', '~> 2.0'
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.0'
  gem 'rubocop-rspec', require: false
end
