name 'complaint-cookbook'
version '1.0.0'
maintainer 'Barclays Chef Team'
maintainer_email 'chef-team@barclays.com'
license 'Apache-2.0'
description 'A test cookbook with BARC rule violations for testing'
source_url 'https://github.com/barclays/complaint-cookbook'

supports 'redhat'
supports 'centos'
supports 'windows'
